#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp

# Extracting parameters Incase right number of arguments is passed.
if [ "$#" -lt 3  ]; then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
    # scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
