#!/usr/bin/env bash
# This script configuring Nginx for a permanent redirection

echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the new configuration
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Reload nginx configuration
service nginx reload