#!/usr/bin/env bash\


# Function to install HAProxy
install_haproxy() {
    sudo apt update
    sudo apt install -y haproxy
}

# Function to configure HAProxy
configure_haproxy() {
    # Backup the original HAProxy configuration file
    sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

    # Create a new HAProxy configuration file
    cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend web-servers

backend web-servers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL

    # Test the HAProxy configuration
    sudo haproxy -c -f /etc/haproxy/haproxy.cfg

    # Restart HAProxy to apply the new configuration
    sudo systemctl restart haproxy
}

# Function to set correct hostnames

# Main execution

# Install HAProxy
install_haproxy

# Configure HAProxy
configure_haproxy
