#!/usr/bin/env bash
# BAsh script that fetches an IP address and pings it 5 times.
IP_ADDRESS="$1"
if [ "$IP_ADDRESS" != "" ]; then
    ping -c 5 "$IP_ADDRESS" 
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
