#!/usr/bin/env bash
# Displays a list of currently running processes i.e all processes, for all users, including those which might not have a TTY
# displayed in a user-oriented format Showing process hierarchy

ps -faux
