#!/usr/bin/env bash
# Displays number 1 to 100 the Fizzbuzz way.

INDEX=1
while [ $INDEX -le 100 ]
do
    if [ $((INDEX%3)) = 0 ] && [ $((INDEX%5)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((INDEX%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((INDEX%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$INDEX"
    fi
        (( INDEX+=1 ))
done
