#!/usr/bin/env bash
# displays username, user id and home path of file  /etc/passwd.

# Open /etc/passwd file for reading
exec 3< /etc/passwd


while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done <&3

# File close descriptor
exec 3<&-
