#!/usr/bin/env bash
# Displays Best School 10 times using a while loop and Hi before the last time.

INDEX=1
while [ $INDEX -le 10 ]
do
    if [ $INDEX = 4 ]
    then
        echo "bad luck"
    elif [ $INDEX = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
        (( INDEX+=1 ))
done
